### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by IDRaykova22** [codingburgas/2324-space-sprint-project-spacio#34]
### Synopsis

Add logo
<hr>

### Required Members:
@niribareva22

**Comment by MVKoleva21** [comment]
![HELP](https://github.com/codingburgas/Spacio/assets/107102793/3d5f99bf-d244-461c-8ebc-7cd1f18f6de4)

**Comment by MVKoleva21** [comment]
![HELP](https://github.com/codingburgas/Spacio/assets/107102793/f7dfbe78-d92c-4244-ab1f-d8072b299e85)
